# This rule is not used by the project gcp-kafka-auth-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gcp-kafka.k8s.onpier.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gcp-kafka-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalkafkauser-viewer-role
rules:
- apiGroups:
  - gcp-kafka.k8s.onpier.de
  resources:
  - externalkafkausers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp-kafka.k8s.onpier.de
  resources:
  - externalkafkausers/status
  verbs:
  - get
