# This rule is not used by the project gcp-kafka-auth-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gcp-kafka.k8s.onpier.de.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gcp-kafka-auth-operator
    app.kubernetes.io/managed-by: kustomize
  name: externalkafkauser-editor-role
rules:
- apiGroups:
  - gcp-kafka.k8s.onpier.de
  resources:
  - externalkafkausers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp-kafka.k8s.onpier.de
  resources:
  - externalkafkausers/status
  verbs:
  - get
