name: Publish a container image

on:
  push:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - file: ./Dockerfile
            name: gcp-kafka-auth-operator
            context: .
          - file: ./Dockerfile.proxy
            name: gcp-kafka-auth-proxy
            context: .
          - file: ./example/test-auth/Containerfile
            name: gcp-kafka-operator-test-auth
            context: ./example/test-auth
          - file: ./example/test-topic-view/Containerfile
            name: gcp-kafka-test-topic-access
            context: ./example/test-topic-view
          - file: ./example/user-tester/Containerfile
            name: gcp-kafka-user-tester
            context: ./example/user-tester
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set the image metadata
        run: ./build/set_image_metadata

      - name: Build an image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.container.name }}-dev
          tags: ${{ env.TAGS }}
          platforms: linux/amd64, linux/arm64/v8
          containerfiles: |
            ${{ matrix.container.file }}
          labels: ${{ env.ANNOTATIONS }}
          context: ${{ matrix.container.context }}
      
      - name: Set the registry in the lower case
        id: registry
        run: |
          echo "registry=$(echo ghcr.io/${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Push the image to GHCR
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ steps.registry.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set the version tag (only if released)
        id: retag-version
        if: (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'edited'))
        run: |
          buildah tag \
          ${{ steps.build-image.outputs.image }}:${{ github.sha }} \
          ${{ steps.registry.outputs.registry }}/${{ matrix.container.name }}:latest
          buildah tag \
          ${{ steps.build-image.outputs.image }}:${{ github.sha }} \
          ${{ steps.registry.outputs.registry }}/${{ matrix.container.name }}:${{ github.event.release.tag_name }}

      - name: Push the release image to GHCR
        if: (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'edited'))
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.registry.outputs.registry }}/${{ matrix.container.name }}:latest ${{ steps.registry.outputs.registry }}/${{ matrix.container.name }}:${{ github.event.release.tag_name }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
